pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Harbor - hlann'
    repository: 'gpt-engineer/gpt-engineer'
    command: 'buildAndPush'
    Dockerfile: 'docker/Dockerfile'
    buildContext: 'gpt-engineer'
    tags: |
      latest
      $(Build.BuildId)
